language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- "./can_auto_deploy.sh && mvn deploy --settings settings.xml"
env:
  global:
  - secure: cWjeHg+yLyxofIGZJ/HAJfWTGWkRLGTDZuGHxEwum6yCptmidZbqnTZRrA07LZvFDP0ecQmTUGTq7D6ImJmFwz1NzgF1ij32JUC0uwewWBm6evQiAzNVcpi++3LB9LWs0cxg4oodYIcSAIfbVExlsHck09oRq3xvRuEtDl9c+ihLbE28FfaawV8CIL7zFA9ACmkRDQCL4kYAZ1RFpLC3XNvH00YDVYy99x2ZGkNlK5QH7yYLETDyBzYUZk3p1RPWuFRikPjMMsOr1hFWkp7p8/DaJdDNojjSrXPbANQc9TQuc6xk4iJqlPwtLkDg2zXQ/JeNXxuSnYH6jX3QmDLCvHlUEs8+cX99fW74CyCepyGSlq4XrxdKoGaE9flle67UIogA6RvjVCVHnMMM24oBhy+m77hV0uGfl9hv8G3OhdIjsIdb33NHhZYHFD9F71ddIbo1ztJCri0R2CLFyyyn446vn16pSPNslcyhmo0w3HbhnKn4vG1wm/k/We9soy7ssh9SFxStkwC2anxXFqIA7oqfw+W0xELXpZLFv9XVmvxoFs5cX/jWLHvfgOsT0Y6ysgDm2BRBCpkmMA6lQK21DRGDZwFx50FMw+hue23eSaEC6RpEH8Y0Di53+jOoxBbVDglKXKHza2zGmHBKCJxAl2ICaZJmgbR+OORwbh67r9Q=
  - secure: BR9R4TreaphRQZ7lLO25hT4FAP4Wva9ZQIumruVY2y/6pbUFYvyGk5kNfA5HXxqOdCYfeF5QAUOmMfJTt2O8im4PGP17gZ4m6SmXrAuGvYtuX1hUD9/J93ByjG0tdscqcSuz+WF5Kaii3VrJnZbDXbnOSLfPyhaQHfWaGFGdXoIO7ZqWgXQxCQZMiWtEQIRtaa9gK3gZ6++SuB5NAGsQbWLINpobrPRgZmyOz8nNwbYwJIdT56v3dUXiS/a3rrVYXYNRIMfiS8x90WQE93CHDUeI8LBAS1UvCJ8GhC53UUhyozuPUrTyoIbZGT9nyDr3qqOHvFLQ/0r6hhWDzyjpMEBSpXf4f9wG2NA22rHa4B9ln9LKGslBZC1kChx0eSnRCrv7C0wJsbEsVNFcw8OHu9odfwkterYPXqCt1VYEo9N3/TRYezesk9WPRd3i9dbcTs9xUbLXhsaAmF0xMgRF6rhJGdfA/l5v6O4gn1477QRJ9/DPB5die4UB3oy6AfNCU/mKlCUSDTN3l8IMvGiYFmqR4G6gjVZD1cEM7zrbEHx4lOnRUeYzhRdYynT004Icyhx2DfG8webpSTccgiA1rEZNeji9mbqyoH4t+xBlkWcZFNnVmSEF+dJx1QK8NEWARHIFGD7qV783T7WIBUqQrSFy+L0GrdGdhny6uZd2B90=
